<main>
  <section class="all-matchs">
    <h2 class="section-title blue">LES MATCHS</h2>
    <?php foreach ($data["games"] as $game) { ?>
      <div class="match-card">
        <h3><?= $game->getName() ?></h3>
        <p class="game-date"><?= $game->getDate() ?></p>
        <div class="game-teams">
          <div class="game-team">
            <img src="<?= $game->getTeam1()->getLogo()->getUrl() ?>" alt="<?= $game->getTeam1()->getLogo()->getAlt() ?>">
          </div>
          <div class="game-team">
            <img src="<?= $game->getTeam2()->getLogo()->getUrl() ?>" alt="<?= $game->getTeam2()->getLogo()->getAlt() ?>">
          </div>
        </div>
        <a href="#" class="btn-discover">VOIR LE MATCH</a>
      </div>
    <?php } ?>
  </section>
</main>
